apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-role-binding
subjects:
- kind: ServiceAccount
  name: debezium-connect
  namespace: $PROJECT
roleRef:
  kind: Role
  name: connector-role
  apiGroup: rbac.authorization.k8s.io