apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-connector
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: "mysql"
    database.port: "3306"
    # database.user: "mysqluser"
    # database.password: "mysqlpw"
    database.user: ${secrets:mysql-secret:user}
    database.password: ${secrets:mysql-secret:password}    
    database.server.id: "184054"
    database.server.name: "dbserver-mysql"

    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: mysql.schema-changes.inventory
       
    table.include.list: inventory.*
    topic.prefix: mysql
